"""Export the OpenAPI schema + the generated IAM vocabulary for the TS side.

Builds the FastAPI app WITHOUT connecting to Postgres/Redis (create_app does no
I/O), dumps a deterministic openapi.json, and emits src/gen/iam.ts from the
Python IAM catalog so the web edge gate and admin UI can never drift from the
API's vocabulary.

Run: `uv run python -m nawa_api.scripts.export_openapi`
"""

import json
from pathlib import Path

import nawa_api  # noqa: F401  (Windows event-loop policy)
from nawa_api.contracts.iam import (
    BUILTIN_GROUPS,
    PERMISSION_META,
    Permission,
)
from nawa_api.runtime.app_factory import create_app

# repo root = .../nawa ; this file = .../nawa/services/api/src/nawa_api/scripts/export_openapi.py
_REPO_ROOT = Path(__file__).resolve().parents[5]
_CONTRACTS = _REPO_ROOT / "packages" / "contracts"
_OPENAPI_JSON = _CONTRACTS / "openapi.json"
_IAM_TS = _CONTRACTS / "src" / "gen" / "iam.ts"

_CONSOLE_SECTIONS = {
    "admin": Permission.CONSOLE_ADMIN,
    "intake": Permission.CONSOLE_INTAKE,
    "journey": Permission.CONSOLE_JOURNEY,
    "reports": Permission.CONSOLE_REPORTS,
}


def export_openapi_json() -> None:
    app = create_app()
    schema = app.openapi()
    _OPENAPI_JSON.parent.mkdir(parents=True, exist_ok=True)
    _OPENAPI_JSON.write_text(
        json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _permission_const_name(value: str) -> str:
    # "nawa:intake:override" -> "INTAKE_OVERRIDE"
    return value.replace("nawa:", "").replace(":", "_").upper()


def export_iam_ts() -> None:
    perms = sorted(PERMISSION_META.keys())
    meta_lines = []
    for p in perms:
        m = PERMISSION_META[p]
        meta_lines.append(
            f'  "{p}": {{ label: {json.dumps(m["label"])}, '
            f"description: {json.dumps(m['description'])}, kind: {json.dumps(m['kind'])} }},"
        )
    const_lines = [f'  {_permission_const_name(p)}: "{p}",' for p in perms]
    union = " | ".join(f'"{p}"' for p in perms)
    group_names = json.dumps(list(BUILTIN_GROUPS.keys()))
    section_lines = [f'  {k}: "{v}",' for k, v in _CONSOLE_SECTIONS.items()]

    ts = f"""// GENERATED by nawa_api.scripts.export_openapi — DO NOT EDIT.
// Mirrors the Python IAM catalog (contracts/iam.py) so client, edge, and server
// share one permission vocabulary.

export const PERMISSIONS = {{
{chr(10).join(const_lines)}
}} as const;

export type Permission = {union};

export interface PermissionMeta {{
  label: string;
  description: string;
  kind: "console" | "feature";
}}

export const PERMISSION_META: Record<Permission, PermissionMeta> = {{
{chr(10).join(meta_lines)}
}};

export const BUILTIN_GROUP_NAMES: string[] = {group_names};

// Console sections gate on these permissions verbatim (design-system §8).
export const CONSOLE_SECTION_PERMISSIONS = {{
{chr(10).join(section_lines)}
}} as const;

// First-match landing surface after login (architecture §15).
export function homeForPermissions(perms: string[]): string {{
  const p = new Set(perms);
  if (p.has("{Permission.CONSOLE_ADMIN}")) return "/admin";
  if (p.has("{Permission.CONSOLE_INTAKE}")) return "/intake";
  if (p.has("{Permission.CONSOLE_REPORTS}")) return "/reports/portfolio";
  if (p.has("{Permission.CONSOLE_JOURNEY}")) return "/journey";
  if (p.has("{Permission.COMMUNITY_READ}")) return "/community";
  return "/onboarding";
}}
"""
    _IAM_TS.parent.mkdir(parents=True, exist_ok=True)
    _IAM_TS.write_text(ts, encoding="utf-8")


def main() -> None:
    export_openapi_json()
    export_iam_ts()
    print(f"Wrote {_OPENAPI_JSON}")
    print(f"Wrote {_IAM_TS}")


if __name__ == "__main__":
    main()
