"""data_spine

Revision ID: ef80b9a4412b
Revises:
Create Date: 2026-07-22 23:53:09.483988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "ef80b9a4412b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions first: gen_random_uuid() needs no extension on PG13+, but
    # citext (case-insensitive email/username) and vector (pgvector) do.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # array_to_string() is STABLE, not IMMUTABLE, in Postgres, so it cannot be
    # called directly inside a GENERATED column expression (founder_profiles
    # .search_tsv below uses it). This thin SQL wrapper is IMMUTABLE and is
    # deterministic for our text[] columns.
    op.execute(
        "CREATE OR REPLACE FUNCTION immutable_array_to_string(text[], text) "
        "RETURNS text AS $$ SELECT array_to_string($1, $2) $$ "
        "LANGUAGE sql IMMUTABLE"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iam_groups",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "policy_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "inline_statements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("managed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iam_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_iam_groups_name")),
    )
    op.create_table(
        "iam_policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "statements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("managed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iam_policies")),
        sa.UniqueConstraint("name", name=op.f("uq_iam_policies_name")),
    )
    op.create_table(
        "programs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name_ar", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("description_ar", sa.String(), nullable=True),
        sa.Column("description_en", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('competition','accelerator','incubation','research_translation','residency','internship')",
            name=op.f("ck_programs_kind"),
        ),
        sa.CheckConstraint(
            "name_ar IS NOT NULL OR name_en IS NOT NULL", name=op.f("ck_programs_name")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
        sa.UniqueConstraint("slug", name=op.f("uq_programs_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("username", postgresql.CITEXT(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), server_default="ar", nullable=False),
        sa.Column("avatar_key", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "attached_policy_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("language IN ('ar','en')", name=op.f("ck_users_language")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(), server_default="user", nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('user','system','ai')", name=op.f("ck_audit_logs_actor_type")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "founder_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("handle", sa.String(), nullable=False),
        sa.Column("display_name_ar", sa.String(), nullable=True),
        sa.Column("display_name_en", sa.String(), nullable=True),
        sa.Column("headline_ar", sa.String(), nullable=True),
        sa.Column("headline_en", sa.String(), nullable=True),
        sa.Column("bio_ar", sa.String(), nullable=True),
        sa.Column("bio_en", sa.String(), nullable=True),
        sa.Column("venture_name_ar", sa.String(), nullable=True),
        sa.Column("venture_name_en", sa.String(), nullable=True),
        sa.Column("venture_summary_ar", sa.String(), nullable=True),
        sa.Column("venture_summary_en", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column(
            "links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("stage", sa.String(), server_default="idea", nullable=False),
        sa.Column(
            "skills", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "domains", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "asks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "is_mentor_eligible", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "kpi_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("kpi_snapshot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(), nullable=True),
        sa.Column("embedding_stale", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple'::regconfig, coalesce(display_name_ar,'') || ' ' || coalesce(display_name_en,'') || ' ' || coalesce(venture_name_ar,'') || ' ' || coalesce(venture_name_en,'') || ' ' || coalesce(headline_ar,'') || ' ' || coalesce(headline_en,'') || ' ' || coalesce(bio_ar,'') || ' ' || coalesce(bio_en,'') || ' ' || immutable_array_to_string(skills,' ') || ' ' || immutable_array_to_string(domains,' '))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('idea','prototype','pilot','revenue','growth')",
            name=op.f("ck_founder_profiles_stage"),
        ),
        sa.CheckConstraint(
            "display_name_ar IS NOT NULL OR display_name_en IS NOT NULL",
            name=op.f("ck_founder_profiles_display_name"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_founder_profiles_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_founder_profiles")),
        sa.UniqueConstraint("handle", name=op.f("uq_founder_profiles_handle")),
        sa.UniqueConstraint("user_id", name=op.f("uq_founder_profiles_user_id")),
    )
    op.create_index(
        "ix_founder_profiles_country_sector",
        "founder_profiles",
        ["country", "sector", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_founder_profiles_directory",
        "founder_profiles",
        ["is_public", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_founder_profiles_domains",
        "founder_profiles",
        ["domains"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_founder_profiles_search_tsv",
        "founder_profiles",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_founder_profiles_skills",
        "founder_profiles",
        ["skills"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "iam_group_members",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["iam_groups.id"],
            name=op.f("fk_iam_group_members_group_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_iam_group_members_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iam_group_members")),
        sa.UniqueConstraint("group_id", "user_id", name=op.f("uq_iam_group_members_group_id")),
    )
    op.create_table(
        "kpi_definitions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name_ar", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("direction", sa.String(), server_default="up_good", nullable=False),
        sa.Column("value_type", sa.String(), server_default="number", nullable=False),
        sa.Column("aggregation", sa.String(), server_default="last", nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "aggregation IN ('last','sum','avg')", name=op.f("ck_kpi_definitions_aggregation")
        ),
        sa.CheckConstraint(
            "direction IN ('up_good','down_good')", name=op.f("ck_kpi_definitions_direction")
        ),
        sa.CheckConstraint(
            "value_type IN ('number','currency','percent','count')",
            name=op.f("ck_kpi_definitions_value_type"),
        ),
        sa.CheckConstraint(
            "name_ar IS NOT NULL OR name_en IS NOT NULL", name=op.f("ck_kpi_definitions_name")
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_kpi_definitions_program_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi_definitions")),
        sa.UniqueConstraint("program_id", "key", name=op.f("uq_kpi_definitions_program_id")),
    )
    op.create_index(
        "uq_kpi_definitions_global_key",
        "kpi_definitions",
        ["key"],
        unique=True,
        postgresql_where=sa.text("program_id IS NULL"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("title_ar", sa.String(), nullable=True),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("body_ar", sa.String(), nullable=True),
        sa.Column("body_en", sa.String(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "title_ar IS NOT NULL OR title_en IS NOT NULL", name=op.f("ck_notifications_title")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_table(
        "program_cycles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name_ar", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','applications_open','screening','active','completed','archived')",
            name=op.f("ck_program_cycles_status"),
        ),
        sa.CheckConstraint(
            "name_ar IS NOT NULL OR name_en IS NOT NULL", name=op.f("ck_program_cycles_name")
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_program_cycles_program_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_cycles")),
        sa.UniqueConstraint("program_id", "slug", name=op.f("uq_program_cycles_program_id")),
    )
    op.create_index(
        "ix_program_cycles_program_status",
        "program_cycles",
        ["program_id", "status", "opens_at"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title_ar", sa.String(), nullable=True),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("description_ar", sa.String(), nullable=True),
        sa.Column("description_en", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("language", sa.String(), server_default="ar", nullable=False),
        sa.Column("steward_user_id", sa.UUID(), nullable=True),
        sa.Column("storage_key", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('handbook','lab_capability','mentor_bio','guide','faq','policy')",
            name=op.f("ck_resources_kind"),
        ),
        sa.CheckConstraint("language IN ('ar','en')", name=op.f("ck_resources_language")),
        sa.CheckConstraint(
            "status IN ('draft','processing','live','archived')", name=op.f("ck_resources_status")
        ),
        sa.CheckConstraint(
            "title_ar IS NOT NULL OR title_en IS NOT NULL", name=op.f("ck_resources_title")
        ),
        sa.ForeignKeyConstraint(
            ["steward_user_id"],
            ["users.id"],
            name=op.f("fk_resources_steward_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resources")),
    )
    op.create_index(
        "ix_resources_status_updated", "resources", ["status", "updated_at"], unique=False
    )
    op.create_index(
        "ix_resources_tags", "resources", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "rubrics",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','retired')", name=op.f("ck_rubrics_status")
        ),
        sa.CheckConstraint(
            "name_ar IS NOT NULL OR name_en IS NOT NULL", name=op.f("ck_rubrics_name")
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["programs.id"], name=op.f("fk_rubrics_program_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rubrics")),
        sa.UniqueConstraint("program_id", "version", name=op.f("uq_rubrics_program_id")),
    )
    op.create_index(
        "uq_rubrics_program_active",
        "rubrics",
        ["program_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_table(
        "site_config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_site_config_updated_by"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_site_config")),
    )
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=True),
        sa.Column("prompt_hash", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tokens_cached", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_estimate", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("request_id", sa.String(), nullable=True),
        sa.Column("cycle_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("subject_type", sa.String(), nullable=True),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ok','error')", name=op.f("ck_ai_calls_status")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_ai_calls_created_by"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["program_cycles.id"],
            name=op.f("fk_ai_calls_cycle_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_calls")),
    )
    op.create_index("ix_ai_calls_created", "ai_calls", ["created_at"], unique=False)
    op.create_index("ix_ai_calls_task_created", "ai_calls", ["task", "created_at"], unique=False)
    op.create_table(
        "anomalies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("kpi_definition_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="open", nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('runway','churn_spike','growth_stall','stalled_milestone','missing_check_in')",
            name=op.f("ck_anomalies_kind"),
        ),
        sa.CheckConstraint(
            "severity IN ('info','warning','critical')", name=op.f("ck_anomalies_severity")
        ),
        sa.CheckConstraint(
            "status IN ('open','acknowledged','resolved','dismissed')",
            name=op.f("ck_anomalies_status"),
        ),
        sa.ForeignKeyConstraint(
            ["kpi_definition_id"],
            ["kpi_definitions.id"],
            name=op.f("fk_anomalies_kpi_definition_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_anomalies_profile_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_anomalies_resolved_by"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomalies")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_anomalies_dedupe_key")),
    )
    op.create_index(
        "ix_anomalies_profile", "anomalies", ["profile_id", "detected_at"], unique=False
    )
    op.create_index(
        "ix_anomalies_status_severity",
        "anomalies",
        ["status", "severity", "detected_at"],
        unique=False,
    )
    op.create_index(
        "uq_anomalies_open_per_kind",
        "anomalies",
        ["profile_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "application_uploads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["program_cycles.id"],
            name=op.f("fk_application_uploads_cycle_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_application_uploads_uploaded_by_user_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_uploads")),
    )
    op.create_index(
        "ix_application_uploads_cycle",
        "application_uploads",
        ["cycle_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "check_ins",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("channel", sa.String(), server_default="conversational", nullable=False),
        sa.Column("language", sa.String(), server_default="ar", nullable=False),
        sa.Column("status", sa.String(), server_default="scheduled", nullable=False),
        sa.Column(
            "transcript",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("summary_ar", sa.String(), nullable=True),
        sa.Column("summary_en", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('conversational','form')", name=op.f("ck_check_ins_channel")
        ),
        sa.CheckConstraint("language IN ('ar','en')", name=op.f("ck_check_ins_language")),
        sa.CheckConstraint(
            "status IN ('scheduled','in_progress','submitted','missed')",
            name=op.f("ck_check_ins_status"),
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["program_cycles.id"],
            name=op.f("fk_check_ins_cycle_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_check_ins_profile_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_ins")),
        sa.UniqueConstraint("profile_id", "period_start", name=op.f("uq_check_ins_profile_id")),
    )
    op.create_index(
        "ix_check_ins_status_period", "check_ins", ["status", "period_start"], unique=False
    )
    op.create_table(
        "cohorts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("name_ar", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=True),
        sa.Column("program_manager_user_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "name_ar IS NOT NULL OR name_en IS NOT NULL", name=op.f("ck_cohorts_name")
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["program_cycles.id"],
            name=op.f("fk_cohorts_cycle_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_manager_user_id"],
            ["users.id"],
            name=op.f("fk_cohorts_program_manager_user_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohorts")),
    )
    op.create_index("ix_cohorts_cycle", "cohorts", ["cycle_id", "starts_at"], unique=False)
    op.create_table(
        "requests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("title_ar", sa.String(), nullable=True),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("details_ar", sa.String(), nullable=True),
        sa.Column("details_en", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column(
            "skills_needed",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("duration_label", sa.String(), nullable=True),
        sa.Column("source", sa.String(), server_default="member", nullable=False),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("outcome_note", sa.String(), nullable=True),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('talent','pilot','review','intro','funding','other')",
            name=op.f("ck_requests_kind"),
        ),
        sa.CheckConstraint(
            "outcome IN ('fulfilled','partially','unfulfilled','withdrawn')",
            name=op.f("ck_requests_outcome"),
        ),
        sa.CheckConstraint("source IN ('member','assistant')", name=op.f("ck_requests_source")),
        sa.CheckConstraint(
            "status IN ('draft','open','matched','closed')", name=op.f("ck_requests_status")
        ),
        sa.CheckConstraint(
            "title_ar IS NOT NULL OR title_en IS NOT NULL", name=op.f("ck_requests_title")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_requests_assigned_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_requests_profile_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
    )
    op.create_index("ix_requests_profile", "requests", ["profile_id", "created_at"], unique=False)
    op.create_index(
        "ix_requests_skills", "requests", ["skills_needed"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_requests_status_created", "requests", ["status", "created_at"], unique=False
    )
    op.create_table(
        "resource_chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "heading_path",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("language", sa.String(), server_default="ar", nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("language IN ('ar','en')", name=op.f("ck_resource_chunks_language")),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
            name=op.f("fk_resource_chunks_resource_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_chunks")),
        sa.UniqueConstraint(
            "resource_id", "chunk_index", name=op.f("uq_resource_chunks_resource_id")
        ),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("source_upload_id", sa.UUID(), nullable=True),
        sa.Column("applicant_name", sa.String(), nullable=False),
        sa.Column("applicant_email", postgresql.CITEXT(), nullable=False),
        sa.Column("source_language", sa.String(), nullable=False),
        sa.Column("original_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "raw_extra",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "normalized",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="submitted", nullable=False),
        sa.Column("ai_total_score", sa.Float(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("normalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_language IN ('ar','en','fr')", name=op.f("ck_applications_source_language")
        ),
        sa.CheckConstraint(
            "status IN ('submitted','normalized','normalize_failed','scored','shortlisted','waitlisted','decided')",
            name=op.f("ck_applications_status"),
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["program_cycles.id"],
            name=op.f("fk_applications_cycle_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_applications_profile_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_upload_id"],
            ["application_uploads.id"],
            name=op.f("fk_applications_source_upload_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
    )
    op.create_index(
        "ix_applications_cycle_status_score",
        "applications",
        ["cycle_id", "status", "ai_total_score", "submitted_at"],
        unique=False,
    )
    op.create_index(
        "ix_applications_cycle_submitted",
        "applications",
        ["cycle_id", "submitted_at"],
        unique=False,
    )
    op.create_index("ix_applications_email", "applications", ["applicant_email"], unique=False)
    op.create_table(
        "assistant_threads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("founder_profile_id", sa.UUID(), nullable=True),
        sa.Column("cohort_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(), server_default="assistant", nullable=False),
        sa.Column("language", sa.String(), server_default="ar", nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('assistant','check_in')", name=op.f("ck_assistant_threads_kind")
        ),
        sa.CheckConstraint("language IN ('ar','en')", name=op.f("ck_assistant_threads_language")),
        sa.CheckConstraint(
            "status IN ('active','archived')", name=op.f("ck_assistant_threads_status")
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohorts.id"],
            name=op.f("fk_assistant_threads_cohort_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["founder_profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_assistant_threads_founder_profile_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assistant_threads_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_threads")),
    )
    op.create_index(
        "ix_assistant_threads_user",
        "assistant_threads",
        ["user_id", "kind", "updated_at"],
        unique=False,
    )
    op.create_table(
        "cohort_members",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), server_default="participant", nullable=False),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('participant','mentor')", name=op.f("ck_cohort_members_role")),
        sa.CheckConstraint(
            "status IN ('active','graduated','withdrawn')", name=op.f("ck_cohort_members_status")
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohorts.id"],
            name=op.f("fk_cohort_members_cohort_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_cohort_members_profile_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cohort_members")),
        sa.UniqueConstraint("cohort_id", "profile_id", name=op.f("uq_cohort_members_cohort_id")),
    )
    op.create_index(
        "ix_cohort_members_profile", "cohort_members", ["profile_id", "joined_at"], unique=False
    )
    op.create_table(
        "digests",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "at_risk",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "upcoming",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("content_ar", sa.String(), nullable=True),
        sa.Column("content_en", sa.String(), nullable=True),
        sa.Column("generated_by", sa.String(), server_default="cron", nullable=False),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "generated_by IN ('cron','manual')", name=op.f("ck_digests_generated_by")
        ),
        sa.CheckConstraint(
            "kind IN ('program_manager','jury','cohort','supervisor')", name=op.f("ck_digests_kind")
        ),
        sa.CheckConstraint(
            "scope_type IN ('cohort','cycle','program')", name=op.f("ck_digests_scope_type")
        ),
        sa.CheckConstraint("status IN ('draft','sent')", name=op.f("ck_digests_status")),
        sa.CheckConstraint(
            "content_ar IS NOT NULL OR content_en IS NOT NULL", name=op.f("ck_digests_content")
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"], ["ai_calls.id"], name=op.f("fk_digests_ai_call_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digests")),
        sa.UniqueConstraint(
            "kind", "scope_type", "scope_id", "period_start", name=op.f("uq_digests_kind")
        ),
    )
    op.create_index(
        "ix_digests_scope", "digests", ["scope_type", "scope_id", "period_start"], unique=False
    )
    op.create_table(
        "kpi_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("kpi_definition_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("source", sa.String(), server_default="check_in", nullable=False),
        sa.Column("check_in_id", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('check_in','manual','import')", name=op.f("ck_kpi_entries_source")
        ),
        sa.ForeignKeyConstraint(
            ["check_in_id"],
            ["check_ins.id"],
            name=op.f("fk_kpi_entries_check_in_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_kpi_entries_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["kpi_definition_id"],
            ["kpi_definitions.id"],
            name=op.f("fk_kpi_entries_kpi_definition_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_kpi_entries_profile_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi_entries")),
        sa.UniqueConstraint(
            "profile_id",
            "kpi_definition_id",
            "period_start",
            name=op.f("uq_kpi_entries_profile_id"),
        ),
    )
    op.create_index(
        "ix_kpi_entries_def_period",
        "kpi_entries",
        ["kpi_definition_id", "period_start"],
        unique=False,
    )
    op.create_index(
        "ix_kpi_entries_profile_def_period",
        "kpi_entries",
        ["profile_id", "kpi_definition_id", "period_start"],
        unique=False,
    )
    op.create_table(
        "mentorships",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("mentor_profile_id", sa.UUID(), nullable=False),
        sa.Column("mentee_profile_id", sa.UUID(), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=True),
        sa.Column("matched_by", sa.String(), server_default="ai", nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rationale_ar", sa.String(), nullable=True),
        sa.Column("rationale_en", sa.String(), nullable=True),
        sa.Column("confirmed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), server_default="suggested", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "matched_by IN ('ai','staff','self')", name=op.f("ck_mentorships_matched_by")
        ),
        sa.CheckConstraint(
            "status IN ('suggested','active','completed','ended')",
            name=op.f("ck_mentorships_status"),
        ),
        sa.CheckConstraint(
            "mentor_profile_id <> mentee_profile_id", name=op.f("ck_mentorships_distinct")
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"],
            ["ai_calls.id"],
            name=op.f("fk_mentorships_ai_call_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"],
            ["cohorts.id"],
            name=op.f("fk_mentorships_cohort_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_id"],
            ["users.id"],
            name=op.f("fk_mentorships_confirmed_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mentee_profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_mentorships_mentee_profile_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mentor_profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_mentorships_mentor_profile_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mentorships")),
    )
    op.create_index(
        "ix_mentorships_mentee", "mentorships", ["mentee_profile_id", "status"], unique=False
    )
    op.create_index(
        "ix_mentorships_mentor", "mentorships", ["mentor_profile_id", "status"], unique=False
    )
    op.create_index(
        "uq_mentorships_active_pair",
        "mentorships",
        ["mentor_profile_id", "mentee_profile_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('suggested','active')"),
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("program_cycle_id", sa.UUID(), nullable=True),
        sa.Column("cohort_id", sa.UUID(), nullable=True),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("scope", sa.String(), server_default="template", nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title_ar", sa.String(), nullable=True),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("description_ar", sa.String(), nullable=True),
        sa.Column("description_en", sa.String(), nullable=True),
        sa.Column("due_offset_days", sa.Integer(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "evidence_required", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'template' AND cohort_id IS NULL) OR (scope = 'cohort' AND cohort_id IS NOT NULL)",
            name=op.f("ck_milestones_scope_shape"),
        ),
        sa.CheckConstraint("scope IN ('template','cohort')", name=op.f("ck_milestones_scope")),
        sa.CheckConstraint(
            "title_ar IS NOT NULL OR title_en IS NOT NULL", name=op.f("ck_milestones_title")
        ),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["cohorts.id"], name=op.f("fk_milestones_cohort_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["program_cycle_id"],
            ["program_cycles.id"],
            name=op.f("fk_milestones_program_cycle_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_milestones_program_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["milestones.id"],
            name=op.f("fk_milestones_template_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestones")),
    )
    op.create_index(
        "ix_milestones_cohort_sequence", "milestones", ["cohort_id", "sequence"], unique=False
    )
    op.create_index(
        "ix_milestones_template_scope",
        "milestones",
        ["program_id", "program_cycle_id", "scope"],
        unique=False,
    )
    op.create_index(
        "uq_milestones_cohort_sequence",
        "milestones",
        ["cohort_id", "sequence"],
        unique=True,
        postgresql_where=sa.text("scope = 'cohort'"),
    )
    op.create_index(
        "uq_milestones_cohort_template",
        "milestones",
        ["cohort_id", "template_id"],
        unique=True,
        postgresql_where=sa.text("template_id IS NOT NULL"),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("posted_by_user_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("title_ar", sa.String(), nullable=True),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("description_ar", sa.String(), nullable=True),
        sa.Column("description_en", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("org_name", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "domains", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "skills", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("ai_tagged", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('internship','job','grant','pilot','speaking','other')",
            name=op.f("ck_opportunities_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','open','matched','closed')", name=op.f("ck_opportunities_status")
        ),
        sa.CheckConstraint(
            "title_ar IS NOT NULL OR title_en IS NOT NULL", name=op.f("ck_opportunities_title")
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"],
            ["ai_calls.id"],
            name=op.f("fk_opportunities_ai_call_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["posted_by_user_id"],
            ["users.id"],
            name=op.f("fk_opportunities_posted_by_user_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_opportunities_profile_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index(
        "ix_opportunities_status_deadline",
        "opportunities",
        ["status", "deadline_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_tags", "opportunities", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("template_key", sa.String(), nullable=True),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("rendered_ar", sa.String(), nullable=True),
        sa.Column("rendered_en", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column("generated_by", sa.String(), server_default="ai", nullable=False),
        sa.Column("export_key", sa.String(), nullable=True),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("generated_by IN ('ai','human')", name=op.f("ck_reports_generated_by")),
        sa.CheckConstraint(
            "kind IN ('founder_monthly','cycle_outcome','impact','internship_evaluation','portfolio')",
            name=op.f("ck_reports_kind"),
        ),
        sa.CheckConstraint("status IN ('draft','review','final')", name=op.f("ck_reports_status")),
        sa.CheckConstraint(
            "subject_type IN ('profile','cycle','program','portfolio')",
            name=op.f("ck_reports_subject_type"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"], ["ai_calls.id"], name=op.f("fk_reports_ai_call_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "kind", "subject_type", "subject_id", "period_start", name=op.f("uq_reports_kind")
        ),
    )
    op.create_index("ix_reports_status_created", "reports", ["status", "created_at"], unique=False)
    op.create_index(
        "ix_reports_subject",
        "reports",
        ["subject_type", "subject_id", "period_start"],
        unique=False,
    )
    op.create_table(
        "request_matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rationale_ar", sa.String(), nullable=True),
        sa.Column("rationale_en", sa.String(), nullable=True),
        sa.Column(
            "matched_skills",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("status", sa.String(), server_default="suggested", nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('suggested','notified','accepted','declined','expired')",
            name=op.f("ck_request_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"],
            ["ai_calls.id"],
            name=op.f("fk_request_matches_ai_call_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_request_matches_profile_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["requests.id"],
            name=op.f("fk_request_matches_request_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_matches")),
        sa.UniqueConstraint("request_id", "profile_id", name=op.f("uq_request_matches_request_id")),
    )
    op.create_index(
        "ix_request_matches_profile", "request_matches", ["profile_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_request_matches_request", "request_matches", ["request_id", "score"], unique=False
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), server_default="attachment", nullable=False),
        sa.Column("extracted_text", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('attachment','cv','deck','extracted_text')",
            name=op.f("ck_application_documents_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_documents_application_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_documents")),
        sa.UniqueConstraint(
            "application_id", "storage_key", name=op.f("uq_application_documents_application_id")
        ),
    )
    op.create_table(
        "application_embeddings",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("source_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_embeddings_application_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("application_id", name=op.f("pk_application_embeddings")),
    )
    op.create_table(
        "assistant_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("language", sa.String(), server_default="ar", nullable=False),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("intent", sa.String(), nullable=True),
        sa.Column("routed_request_id", sa.UUID(), nullable=True),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "intent IN ('informational','operational')", name=op.f("ck_assistant_messages_intent")
        ),
        sa.CheckConstraint("language IN ('ar','en')", name=op.f("ck_assistant_messages_language")),
        sa.CheckConstraint(
            "role IN ('user','assistant','system','route')", name=op.f("ck_assistant_messages_role")
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"],
            ["ai_calls.id"],
            name=op.f("fk_assistant_messages_ai_call_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["routed_request_id"],
            ["requests.id"],
            name=op.f("fk_assistant_messages_routed_request_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["assistant_threads.id"],
            name=op.f("fk_assistant_messages_thread_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_messages")),
    )
    op.create_index(
        "ix_assistant_messages_thread",
        "assistant_messages",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column(
            "previous_value",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "new_value",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('shortlist','waitlist','advance','reject','accept','override_score')",
            name=op.f("ck_decisions_decision"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_decisions_application_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_decisions_decided_by"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index(
        "ix_decisions_application", "decisions", ["application_id", "created_at"], unique=False
    )
    op.create_table(
        "dedup_matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("matched_application_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','confirmed','dismissed')", name=op.f("ck_dedup_matches_status")
        ),
        sa.CheckConstraint(
            "application_id <> matched_application_id", name=op.f("ck_dedup_matches_distinct")
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_dedup_matches_application_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["matched_application_id"],
            ["applications.id"],
            name=op.f("fk_dedup_matches_matched_application_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_dedup_matches_reviewed_by"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dedup_matches")),
        sa.UniqueConstraint(
            "application_id", "matched_application_id", name=op.f("uq_dedup_matches_application_id")
        ),
    )
    op.create_index(
        "ix_dedup_matches_application",
        "dedup_matches",
        ["application_id", "similarity"],
        unique=False,
    )
    op.create_table(
        "milestone_progress",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("milestone_id", sa.UUID(), nullable=False),
        sa.Column("cohort_member_id", sa.UUID(), nullable=False),
        sa.Column("founder_profile_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), server_default="not_started", nullable=False),
        sa.Column("note_ar", sa.String(), nullable=True),
        sa.Column("note_en", sa.String(), nullable=True),
        sa.Column(
            "evidence_links",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('not_started','in_progress','submitted','blocked','done','waived')",
            name=op.f("ck_milestone_progress_status"),
        ),
        sa.ForeignKeyConstraint(
            ["cohort_member_id"],
            ["cohort_members.id"],
            name=op.f("fk_milestone_progress_cohort_member_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["founder_profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_milestone_progress_founder_profile_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
            name=op.f("fk_milestone_progress_milestone_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_milestone_progress_reviewed_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_milestone_progress_updated_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_milestone_progress")),
        sa.UniqueConstraint(
            "milestone_id", "cohort_member_id", name=op.f("uq_milestone_progress_milestone_id")
        ),
    )
    op.create_index(
        "ix_milestone_progress_member",
        "milestone_progress",
        ["cohort_member_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_milestone_progress_profile",
        "milestone_progress",
        ["founder_profile_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_milestone_progress_status_updated",
        "milestone_progress",
        ["status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rationale_ar", sa.String(), nullable=True),
        sa.Column("rationale_en", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="suggested", nullable=False),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('suggested','notified','interested','applied','accepted','declined')",
            name=op.f("ck_opportunity_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"],
            ["ai_calls.id"],
            name=op.f("fk_opportunity_matches_ai_call_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_matches_opportunity_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["founder_profiles.id"],
            name=op.f("fk_opportunity_matches_profile_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_matches")),
        sa.UniqueConstraint(
            "opportunity_id", "profile_id", name=op.f("uq_opportunity_matches_opportunity_id")
        ),
    )
    op.create_index(
        "ix_opportunity_matches_profile",
        "opportunity_matches",
        ["profile_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "scorecards",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("rubric_id", sa.UUID(), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("rationale_ar", sa.String(), nullable=True),
        sa.Column("rationale_en", sa.String(), nullable=True),
        sa.Column("hidden_gem", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("hidden_gem_reason_ar", sa.String(), nullable=True),
        sa.Column("hidden_gem_reason_en", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("ai_call_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), server_default="generated", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('ai','human')", name=op.f("ck_scorecards_source")),
        sa.CheckConstraint(
            "status IN ('generated','reviewed','final')", name=op.f("ck_scorecards_status")
        ),
        sa.ForeignKeyConstraint(
            ["ai_call_id"],
            ["ai_calls.id"],
            name=op.f("fk_scorecards_ai_call_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_scorecards_application_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id"], ["rubrics.id"], name=op.f("fk_scorecards_rubric_id"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scorecards")),
        sa.UniqueConstraint(
            "application_id", "rubric_id", "source", name=op.f("uq_scorecards_application_id")
        ),
    )
    op.create_index(
        "ix_scorecards_application", "scorecards", ["application_id", "created_at"], unique=False
    )
    op.create_table(
        "scorecard_criteria",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("scorecard_id", sa.UUID(), nullable=False),
        sa.Column("criterion_key", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("rationale_ar", sa.String(), nullable=True),
        sa.Column("rationale_en", sa.String(), nullable=True),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scorecard_id"],
            ["scorecards.id"],
            name=op.f("fk_scorecard_criteria_scorecard_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scorecard_criteria")),
        sa.UniqueConstraint(
            "scorecard_id", "criterion_key", name=op.f("uq_scorecard_criteria_scorecard_id")
        ),
    )
    # ### end Alembic commands ###

    # HNSW cosine indexes — autogenerate does not emit these; hand-written
    # per 03-data-spine.md §6. pgvector defaults: m=16, ef_construction=64.
    op.execute(
        "CREATE INDEX ix_founder_profiles_embedding_hnsw ON founder_profiles "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_resource_chunks_embedding_hnsw ON resource_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_application_embeddings_embedding_hnsw ON application_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse of the HNSW creation above — drop before the tables that carry them.
    op.execute("DROP INDEX IF EXISTS ix_application_embeddings_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_resource_chunks_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_founder_profiles_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scorecard_criteria")
    op.drop_index("ix_scorecards_application", table_name="scorecards")
    op.drop_table("scorecards")
    op.drop_index("ix_opportunity_matches_profile", table_name="opportunity_matches")
    op.drop_table("opportunity_matches")
    op.drop_index("ix_milestone_progress_status_updated", table_name="milestone_progress")
    op.drop_index("ix_milestone_progress_profile", table_name="milestone_progress")
    op.drop_index("ix_milestone_progress_member", table_name="milestone_progress")
    op.drop_table("milestone_progress")
    op.drop_index("ix_dedup_matches_application", table_name="dedup_matches")
    op.drop_table("dedup_matches")
    op.drop_index("ix_decisions_application", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_assistant_messages_thread", table_name="assistant_messages")
    op.drop_table("assistant_messages")
    op.drop_table("application_embeddings")
    op.drop_table("application_documents")
    op.drop_index("ix_request_matches_request", table_name="request_matches")
    op.drop_index("ix_request_matches_profile", table_name="request_matches")
    op.drop_table("request_matches")
    op.drop_index("ix_reports_subject", table_name="reports")
    op.drop_index("ix_reports_status_created", table_name="reports")
    op.drop_table("reports")
    op.drop_index("ix_opportunities_tags", table_name="opportunities", postgresql_using="gin")
    op.drop_index("ix_opportunities_status_deadline", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(
        "uq_milestones_cohort_template",
        table_name="milestones",
        postgresql_where=sa.text("template_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_milestones_cohort_sequence",
        table_name="milestones",
        postgresql_where=sa.text("scope = 'cohort'"),
    )
    op.drop_index("ix_milestones_template_scope", table_name="milestones")
    op.drop_index("ix_milestones_cohort_sequence", table_name="milestones")
    op.drop_table("milestones")
    op.drop_index(
        "uq_mentorships_active_pair",
        table_name="mentorships",
        postgresql_where=sa.text("status IN ('suggested','active')"),
    )
    op.drop_index("ix_mentorships_mentor", table_name="mentorships")
    op.drop_index("ix_mentorships_mentee", table_name="mentorships")
    op.drop_table("mentorships")
    op.drop_index("ix_kpi_entries_profile_def_period", table_name="kpi_entries")
    op.drop_index("ix_kpi_entries_def_period", table_name="kpi_entries")
    op.drop_table("kpi_entries")
    op.drop_index("ix_digests_scope", table_name="digests")
    op.drop_table("digests")
    op.drop_index("ix_cohort_members_profile", table_name="cohort_members")
    op.drop_table("cohort_members")
    op.drop_index("ix_assistant_threads_user", table_name="assistant_threads")
    op.drop_table("assistant_threads")
    op.drop_index("ix_applications_email", table_name="applications")
    op.drop_index("ix_applications_cycle_submitted", table_name="applications")
    op.drop_index("ix_applications_cycle_status_score", table_name="applications")
    op.drop_table("applications")
    op.drop_table("resource_chunks")
    op.drop_index("ix_requests_status_created", table_name="requests")
    op.drop_index("ix_requests_skills", table_name="requests", postgresql_using="gin")
    op.drop_index("ix_requests_profile", table_name="requests")
    op.drop_table("requests")
    op.drop_index("ix_cohorts_cycle", table_name="cohorts")
    op.drop_table("cohorts")
    op.drop_index("ix_check_ins_status_period", table_name="check_ins")
    op.drop_table("check_ins")
    op.drop_index("ix_application_uploads_cycle", table_name="application_uploads")
    op.drop_table("application_uploads")
    op.drop_index(
        "uq_anomalies_open_per_kind",
        table_name="anomalies",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_anomalies_status_severity", table_name="anomalies")
    op.drop_index("ix_anomalies_profile", table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index("ix_ai_calls_task_created", table_name="ai_calls")
    op.drop_index("ix_ai_calls_created", table_name="ai_calls")
    op.drop_table("ai_calls")
    op.drop_table("site_config")
    op.drop_table("sessions")
    op.drop_index(
        "uq_rubrics_program_active",
        table_name="rubrics",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("rubrics")
    op.drop_index("ix_resources_tags", table_name="resources", postgresql_using="gin")
    op.drop_index("ix_resources_status_updated", table_name="resources")
    op.drop_table("resources")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_program_cycles_program_status", table_name="program_cycles")
    op.drop_table("program_cycles")
    op.drop_table("notifications")
    op.drop_index(
        "uq_kpi_definitions_global_key",
        table_name="kpi_definitions",
        postgresql_where=sa.text("program_id IS NULL"),
    )
    op.drop_table("kpi_definitions")
    op.drop_table("iam_group_members")
    op.drop_index(
        "ix_founder_profiles_skills", table_name="founder_profiles", postgresql_using="gin"
    )
    op.drop_index(
        "ix_founder_profiles_search_tsv", table_name="founder_profiles", postgresql_using="gin"
    )
    op.drop_index(
        "ix_founder_profiles_domains", table_name="founder_profiles", postgresql_using="gin"
    )
    op.drop_index("ix_founder_profiles_directory", table_name="founder_profiles")
    op.drop_index("ix_founder_profiles_country_sector", table_name="founder_profiles")
    op.drop_table("founder_profiles")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("programs")
    op.drop_table("iam_policies")
    op.drop_table("iam_groups")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS immutable_array_to_string(text[], text)")

    # Extensions dropped last, after every table that depends on them.
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP EXTENSION IF EXISTS citext")
